/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hz202.hwk2;

import java.io.StringBufferInputStream;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
      StringBufferInputStream s0 = new	StringBufferInputStream("ss\ns\na\n\nsss\nswsw\nh2m\ns9v\ns8v\nt9v\nt9h\nr7v\nr6v\nr5v\nu1v\ns1u\nq0r\ns2d\nn8u\np0r\ni9d\n\n\na8h\nb8h\na5h\nb5h\nc5h\nc9l\ns1u\nr8r\na0l\nn0u\nd0r\n\n\ns\ntt\nm\ntt\na\ns\nt9\n\nm\nss\nm\nr8\no8r\n\nd\na0\n\nd\nt9\n\nd\na1\n\nd\na1\n\nd\na2\n\nd\na2\n\nd\nss\nb2\n\nd\na2\n\nd\nb3\n\nd\nb3\n\nd\nb4\n\nd\nb4\n\nd\na5\n\nd\na5\n\nd\na6\n\nd\na6\n\nd\na7\n\nd\na7\n\nd\na8\n\nd\na8\n\nd\na9\n\nd\na9\n\nd\nb5\n\nd\nb5\n\nd\nb6\n\nd\nb6\n\nd\nb7\n\nd\nb7\n\nd\nb8\n\nd\nb8\n\nd\nb9\n\nd\nb9\n\nd\nc2\n\nd\nc2\n\nd\nc3\n\nd\nc3\n\nd\nc4\n\nd\nc4\n\nd\nc5\n\nd\nc5\n\nd\nc6\n\nd\nc6\n\nd\nc7\n\nd\nc7\n\nd\nc9\n\nd\nc9\n\nd\nd0\n\nd\nd0\n\nd\nd1\n\nd\nd1\n\nd\nd2\n\nd\nd2\n\nd\nd9\n\nd\nd9\n\nd\nd8\n\nd\nd8\n\nd\ne9\n\nd\ne9\n\nd\nn0\n\nd\nn0\n\nd\no0\n\nd\no0\n\nd\np0\n\nd\np0\n\nd\np1\n\nd\np1\n\nd\nq1\n\nd\nq1\n\nd\nr1\n\nd\nr1\n\nd\ns1\n\nd\ns1\n\nd\nt1\n\nd\nt1\n\nd\nt0\n\nd\nt0\n\nd\nt2\n\nd\nt2\n\nd\no8\n\nd\no8\n\nd\np8\n\nd\np8\n\nd\nq8\n\nd\nq8\n\nd\np9\n\nd\np9\n\nd\np9\n\nd\np9\n\ns\nc6\n\ns\nc6\n\nm\ns9\nj9h\n\nm\nh5\n\nm\ns9\nk9v\n\nm\nk9\nk9v\n\nm\nk9\nk9v\n\nm\nk9\nk9v\n\nm\nk9\ns9v\n\nm\nb8\ni4h\ns\nu9\n\ns\nu9\n\nd\nb2\n\nd\nb2\n\n"); 
	System.setIn(s0);
      sallysStash ss0 = new sallysStash();
      ss0.startGame();

      StringBufferInputStream s1 = new	StringBufferInputStream("ss\ns\na\n\nsss\nswsw\nh2m\nu2h\ns9v\ns8h\nr9v\ns8v\nt9v\nt9h\nr7v\nr6v\nr5v\nu1v\ns9u\nt9u\nr9r\ns8r\ns8d\nt7d\ns1l\nr0l\ns1u\nq0r\ns2d\nn8u\np0r\nr8u\no9u\na0r\nt9r\nt9d\nt9l\no0d\nt0l\nr7l\nssss\nsss\nk5m\no4u\ni9d\n\n\na8h\nb8h\na5h\nb5h\nc5h\nc9l\ns1u\nr8r\na0l\nn0u\nd0r\n\n\ns\ns\ns\ni5\n\ns\ni5\n\ni5\n\ns\ni5\n\ns\ni5\n\ns\ni5\n\ns\nd\nt0\n\nd\nt0\n\nd\nt1\n\nd\nt1\n\nd\nt2\n\nd\nt2\n\nd\nt3\n\nd\nt3\n\nd\nt5\n\nd\nt5\n\nd\nt6\n\nd\nt6\n\nd\nt7\n\nd\nt7\n\nd\nt8\n\nd\nt8\n\nd\nt9\n\nd\nt9\n\nd\ns0\n\nd\ns0\n\nd\ns1\n\nd\ns1\n\nd\ns2\n\nd\ns2\n\nd\ns3\n\nd\ns3\n\nd\ns4\n\nd\ns4\n\nd\ns5\n\nd\ns5\n\nd\ns6\n\nd\ns6\n\nd\ns7\n\nd\ns7\n\nd\ns8\n\nd\ns8\n\nd\ns9\n\nd\ns9\n\nd\nr0\n\nd\nr0\n\nd\nq0\n\nd\nq0\n\nd\np0\n\nd\np0\n\nd\nr1\n\nd\nr1\n\nd\np1\n\nd\np1\n\nd\np2\n\nd\np2\n\nd\no2\n\nd\no2\n\nd\no3\n\nd\no3\n\nd\no4\n\nd\no4\n\nd\nr5\n\nd\nr5\n\nd\nr6\n\nd\nr6\n\nd\nr7\n\nd\nr7\n\nd\nr9\n\nd\nr9\n\nd\nq9\n\nd\nq9\n\nd\np9\n\nd\np9\n\nd\np8\n\nd\np8\n\nd\no8\n\nd\no8\n\nd\nn8\n\nd\nn8\n\nd\nm8\n\nd\nm8\n\nd\nl8\n\nd\nl8\n\nd\nk8\n\nd\nk8\n\nd\nk9\n\nd\nk9\n\nd\nj9\n\nd\nj9\n\nd\ni9\n\nd\nsss\nd\nu9\nm\nsss\nm\nu9\nm\nss\nm\na8\nsss\nm\na8\nss\nm\na8\nu9v\nm\na8\nt9h\nm\na8\nt9v\nm\na8\ni5m\nm\na8\na4h\nm\na8\na4v\nm\nd0\nddd\nm\nd0\ndd\nm\nd0\nf9r\nm\nd0\ni4i\nm\nd0\nl0u\nm\na8\nd3v\n\nd\ni9\n\nd\ni9\n\n");
System.setIn(s1);
      sallysStash ss1 = new sallysStash();
      ss1.startGame();
        ///App classUnderTest = new App();
        ///assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
	StringBufferInputStream s2 = new StringBufferInputStream("d\n");
    System.setIn(s2);
    sallysStash ss2 = new sallysStash();
    ss2.startGame();
	StringBufferInputStream s3 = new StringBufferInputStream("d\n");
    System.setIn(s3);
	sallysStash ss3 = new sallysStash();
    ss3.startGame();
	StringBufferInputStream s4 = new StringBufferInputStream("d\n");
    System.setIn(s4);
	sallysStash ss4 = new sallysStash();
    ss4.startGame();
	
    }
}
