/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hz202.hwk2;

import java.util.Scanner;

public class App {
  /*public String getGreeting() {
        return "Hello world.";
        }*/

    public static void main(String[] args) {
      sallysStash new_game = new sallysStash();
      new_game.startGame();
  }
        ///System.out.println(new App().getGreeting());
    }

